export const QUEUE_NAME = {
  JIRA_SYNC: 'jira-sync',
  AI_ANALYSIS: 'ai-analysis',
  GIT_OPERATION: 'git-operation',
  NOTIFICATION: 'notification',
} as const;

export const QUEUE_PROCESSOR = {
  JIRA_SYNC: {
    SYNC_PROJECTS: 'SYNC_PROJECTS',
    SYNC_SPRINTS: 'SYNC_SPRINTS',
    SYNC_VERSIONS: 'SYNC_VERSIONS',
    SYNC_TICKETS: 'SYNC_TICKETS',
    SYNC_SPRINT_TICKETS: 'SYNC_SPRINT_TICKETS',
    SYNC_VERSION_TICKETS: 'SYNC_VERSION_TICKETS',
    SYNC_TICKET_COMMENTS: 'SYNC_TICKET_COMMENTS',
    SYNC_TICKET_WORKLOGS: 'SYNC_TICKET_WORKLOGS',
    SYNC_ALL: 'SYNC_ALL',
  },
  AI_ANALYSIS: {
    ANALYZE_TICKET: 'ANALYZE_TICKET',
    APPLY_CODE: 'APPLY_CODE',
  },
  GIT_OPERATION: {
    FULL_APPROVE_FLOW: 'FULL_APPROVE_FLOW',
  },
  NOTIFICATION: {
    SEND_TELEGRAM: 'SEND_TELEGRAM',
    SEND_WEB: 'SEND_WEB',
  },
} as const;
